---
- name: Install Mobot packages
  apt:
    name: "{{ 'ros-' + ros2_distribution + '-mobot-bringup' }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install extra packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages: "{{ 'ros-' + ros2_distribution + '-' + item }}"
  with_items: "{{ mobot_extra_ros_packages }}"
  when: (mobot_extra_ros_packages is defined) and (mobot_extra_ros_packages is not none)
  become: true
